### ISSUE TITLE
Could not find artifact org.openapitools:openapi-java-client:pom:1.0.258 in central (https://repo1.maven.org/maven2)

### ISSUE THREAD

**Issue by douglundin** [turnitin/tca-client-java#1]
Is there a problem with the instructions that lead to this error:
Could not find artifact org.openapitools:openapi-java-client:pom:1.0.258 in central (https://repo1.maven.org/maven2)

**Comment by baholladay** [comment]
I tested and was able to compile the project successfully. Make sure you have your repo cleared and your maven settings correct and follow the install instructions.
